services:
  - type: web
    name: asura-md-bot
    runtime: docker 
    plan: free
    envVars:
      - key: SESSION_ID
        sync: false
        placeholder: "Your SESSION_ID"
      - key: PREFIX
        value: "."

